config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/cats')

  resource :user, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :cats, except: :destroy

  resources :cat_rental_requests, path: :requests, as: :requests, only: [:new, :create] do
    post 'approve', on: :member
    post 'deny', on: :member
  end
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = {
    "R" => "Red",
    "O" => "Orange",
    "Y" => "Yellow",
    "G" => "Green",
    "B" => "Blue",
    "I" => "Indigo",
    "V" => "Violet"
  }

  SEXES = { "M" => "Male", "F" => "Female" }

  validates(
    :birth_date,
    :color,
    :name,
    :sex,
    :description,
    :user_id,
    presence: true
    )

  validates :sex, inclusion: SEXES.keys
  validates :color, inclusion: COLORS.keys
  validate :birth_date_not_in_future

  belongs_to :owner,
    class_name: "User",
    foreign_key: :user_id

  has_many :cat_rental_requests, dependent: :destroy

  def age
    now = Date.today
    now.year - Date.parse(birth_date).year
  end

  def sorted_requests
    cat_rental_requests.order(:start_date)
  end

  private
  def birth_date_not_in_future
    if !birth_date.empty? && (Date.parse(birth_date) > Date.today)
      errors[:birth_date_range] << "is not valid."
    end
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  STATUSES = %w(PENDING APPROVED DENIED)

  validates :cat_id, :start_date, :end_date, :user_id, presence: true
  validates :status, inclusion: STATUSES
  validate :request_does_not_overlap_with_approved
  validate :start_date_comes_before_end_date

  belongs_to :cat

  belongs_to :requester,
    class_name: "User",
    foreign_key: :user_id

  def approve!
    transaction do
      overlapping_pending_requests.update_all(status: 'DENIED')
      self.update(status: 'APPROVED')
    end
  end

  def approved?
    self.status == "APPROVED"
  end

  def deny!
    self.update(status: 'DENIED')
  end

  def denied?
    self.status == "DENIED"
  end

  def pending?
    self.status == "PENDING"
  end

  private
  def overlapping_requests
    self.class
      .where("(:id IS NULL) OR (id != :id)", id: self.id)
      .where(cat_id: self.cat_id)
      .where.not(<<-SQL, start_date: self.start_date, end_date: self.end_date)
        (start_date > :end_date) OR (end_date < :start_date)
      SQL
  end

  def overlapping_pending_requests
    overlapping_requests.where(status: 'PENDING')
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: 'APPROVED')
  end

  def request_does_not_overlap_with_approved
    return if self.denied?

    unless overlapping_approved_requests.empty?
      errors[:request] << "has time overlap with an approved request"
    end
  end

  def start_date_comes_before_end_date
    return if self.start_date < self.end_date
    errors[:start_date] << "must come before end date"
    errors[:end_date] << "must come after start date"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  after_initialize :set_session_token

  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :cats, dependent: :destroy

  has_many :requests,
    class_name: "CatRentalRequest",
    foreign_key: :user_id

  def self.find_by_credentials(username, password)
    user = self.find_by(username: username)

    if user
      user.is_password?(password) ? user : nil
    else
      nil
    end
  end

  def is_password?(password)
    digest = BCrypt::Password.new(self.password_digest)
    digest.is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def generate_session_token
    self.session_token = SecureRandom::urlsafe_base64
  end

  def set_session_token
    self.session_token || generate_session_token
  end

  def reset_session_token!
    generate_session_token
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    current_session_token = session[:session_token]
    @current_user ||= User.find_by(session_token: current_session_token)
  end

  def login_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def prevent_signup_or_login_if_logged_in
    redirect_to cats_url if current_user
  end

  def ensure_current_user_is_cat_owner
    cat_id = params[:id]
    found_cat = current_user.cats.where(id: cat_id)
    redirect_to cats_url if found_cat.empty?
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :ensure_current_user_is_cat_owner, only: [:approve, :deny]

  def new
    @request = CatRentalRequest.new
    @cats = Cat.all
    render :new
  end

  def create
    @request = CatRentalRequest.new(request_params)
    if @request.save
      redirect_to cat_url(@request.cat_id)
    else
      @cats = Cat.all
      render :new
    end
  end

  def approve
    @request = CatRentalRequest.find(params[:id])
    @request.approve!
    redirect_to cat_url(@request.cat_id)
  end

  def deny
    @request = CatRentalRequest.find(params[:id])
    @request.deny!
    redirect_to cat_url(@request.cat_id)
  end

  private
  def request_params
    attributes = [:cat_id, :start_date, :end_date]
    params.require(:request).permit(attributes)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :ensure_logged_in_to_register_cat, only: [:new, :create]
  before_action :ensure_current_user_is_cat_owner, only: [:edit, :update]

  def index
    @cats = Cat.all
    render :index
  end

  def create
    @cat = current_user.cats.new(cat_params)
    if @cat.save
      render :show
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def new
    @cat = Cat.new
    render :new
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  private
  def cat_params
    attributes = [:name, :birth_date, :color, :sex, :description]
    params.require(:cat).permit(attributes)
  end

  def ensure_logged_in_to_register_cat
    redirect_to new_session_url unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :prevent_signup_or_login_if_logged_in, only: [:new, :create]

  def new
    @user = User.new
    render :login
  end

  def create
    username, password = session_params[:username], session_params[:password]
    @user = User.find_by_credentials(username, password)
    if @user
      login_user!(@user)
      redirect_to cats_url
    else
      flash.now[:errors] = ["Login failed!"]
      render :login
    end
  end

  def destroy
    if current_user
      current_user.reset_session_token!
      session[:session_token] = nil
    end

    redirect_to cats_url
  end

  private
  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :prevent_signup_or_login_if_logged_in, only: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to cats_url
    else
      flash[:errors] = ["Login failed"]
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<h1>Rent a Cat!</h1>

<%= render "shared/errors" %>

<form action="<%= requests_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <table>
    <tr>
      <td>
        <label for="request_cat_id">Cat ID &amp; Name:</label>
      </td>
      <td>
        <select
          name="request[cat_id]"
          value="<%= @request.cat_id %>"
          id="request_cat_id">
          <option></option>
          <% @cats.each do |cat| %>
            <option
              value="<%= cat.id %>"
              <%= "selected" if @request.cat_id == cat.id %>>
              <%= "(#{cat.id}) #{cat.name}" %>
            </option>
          <% end %>
        </select>
      </td>
    </tr>
    <tr>
      <td>
        <label for="request_start_date]">Start Date:</label>
      </td>
      <td>
        <input
          type="date"
          name="request[start_date]"
          id="request_start_date"
          value="<%= @request.start_date %>">
      </td>
    </tr>
    <tr>
      <td>
        <label for="request_end_date">End Date:</label>
      </td>
      <td>
        <input
          type="date"
          name="request[end_date]"
          id="request_end_date"
          value="<%= @request.end_date %>">
      </td>
    </tr>
  </table>

  <input type="submit" value="Submit Rental Request">
</form>

app/views/cats/_form.html.erb
<% action = (@cat.persisted? ? cat_url(@cat) : cats_url) %>
<% method = (@cat.persisted? ? :patch : :post) %>
<% submit_text = (@cat.persisted? ? "Update" : "Submit") %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <table>
    <tr>
      <td>
        <label for="cat_name">Name: </label>
      </td>
      <td>
        <input
          type="text"
          name="cat[name]"
          id="cat_name"
          value="<%= @cat.name %>">
      </td>
    </tr>

    <tr>
      <td>
        <label for="cat_sex">Sex: </label>
      </td>
      <td>
        <% Cat::SEXES.each do |sex_abbrev, sex| %>
          <input
            type="radio"
            name="cat[sex]"
            id="cat_sex"
            value="<%= sex_abbrev %>"
            <%= "checked" if @cat.sex == sex_abbrev %>>
            <label for="cat[sex]"><%= sex %></label>
        <% end %>
      </td>
    </tr>

    <tr>
      <td>
        <label for="cat[color]">Color: </label>
      </td>
      <td>
        <select name="cat_color" value="<%= @cat.color %>">
          <option></option>
          <% Cat::COLORS.each do |color_code, color| %>
            <option
              value="<%= color_code %>"
              <%= "selected" if @cat.color == color_code %>>
              <%= color %>
            </option>
          <% end %>
        </select>
      </td>
    </tr>
    <tr>
      <td>
        <label for="cat_birth_date">Birth Date: </label>
      </td>
      <td>
        <input
          type="date"
          name="cat[birth_date]"
          input="cat_description"
          value="<%= @cat.birth_date %>">
      </td>
    </tr>
    <tr>
      <td>
        <label for="cat_description">Description: </label>
      </td>
      <td>
        <textarea name="cat[description]" rows="8" cols="40"><%= @cat.description %></textarea>
      </td>
    </tr>
  </table>

  <input type="submit" value="<%= submit_text %>">
</form>

app/views/cats/_request_tr.html.erb
  <tr>
    <td>
      <%= request.requester.username %>
    </td>
    <td>
      <%= request.start_date %>
    </td>
    <td>
      <%= request.end_date %>
    </td>
    <td>
      <%= request.status.capitalize %>
    </td>
    <% if cat.owner == current_user && request.pending? %>
    <td>
        <%= button_to "Approve", approve_request_url(request.id) %>
    </td>
    <td>
        <%= button_to "Deny", deny_request_url(request.id) %>
    </td>
    <% end %>
  </tr>

app/views/cats/edit.html.erb
<h1>Update your cat!</h1>

<%= render "shared/errors" %>
<%= render "form" %>

app/views/cats/index.html.erb
<h1>99CATS</h1>

<table>
  <% @cats.each do |cat| %>
    <tr>
      <td>
        <%= link_to cat.name, cat_url(cat) %>: <%= cat.description %>
      </td>
    </tr>
  <% end %>
</table>
<br/>
<% if current_user %>
  <%= link_to "Register your cat", new_cat_url %>
<% end %>

app/views/cats/new.html.erb
<h1>Register your cat for rental!</h1>

<%= render "shared/errors" %>
<%= render "form" %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <tr>
    <td>Age:</td>
    <td><%= @cat.age %></td>
  </tr>
  <tr>
    <td>Color:</td>
    <td><%= Cat::COLORS[@cat.color] %></td>
  </tr>
  <tr>
    <td>Sex:</td>
    <td><%= Cat::SEXES[@cat.sex] %></td>
  </tr>
  <tr>
    <td>Description:</td>
    <td><%= @cat.description %></td>
  </tr>
</table>

<h3>Rental Requests</h3>
<table>
  <tr>
    <th>Requester</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Status</th>
  </tr>
  <% @cat.sorted_requests.includes(:requester).each do |request| %>
    <%= render "request_tr", request: request, cat: @cat %>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <table>
    <tr>
      <td>
        <%= current_user.username %>
      </td>
      <td>
        <%= button_to "Logout", session_url, method: :delete %>
      </td>
    </tr>
  </table>
<% else %>
  <table>
    <tr>
      <td>
        <%= button_to "Sign up", new_user_url, method: :get %>
      </td>
      <td>
        <%= button_to "Login", new_session_url, method: :get %>
      </td>
    </tr>
  </table>
<% end %>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <p>
    <% flash[:errors].each do |error| %>
      <%= error %><br/>
    <% end %>
  </p>
<% end %>

app/views/shared/_user_form.html.erb
<% username = (user ? user.username : "") %>

<form action="<%= action %>", method="post">
  <table>
    <tr>
      <td>
        <label for="username">Username:</label>
      </td>
      <td>
        <input
          type="text"
          name="<%= input %>[username]"
          id="username"
          value="<%= user.username %>">
      </td>
    </tr>
    <tr>
      <td>
        <label for="password">Password:</label>
      </td>
      <td>
        <input
          type="password"
          name="<%= input %>[password]"
          id="password"
          value = "">
      </td>
    </tr>
  </table>

  <%= button_to button, action, method: :post %>
</form>

app/views/users/new.html.erb
<h1>Create your account</h1>

<% options = {
  user: @user,
  action: user_url,
  input: :user,
  button: "Create an account"
  } %>

<%= render "shared/errors" %>
<%= render "shared/user_form", options %>